CoreFirebase/Models/DataContext.cs
using Microsoft.EntityFrameworkCore;

namespace CoreFirebase.Models
{
    public class DataContext:DbContext
    {
        public DataContext(DbContextOptions<DataContext> options) : base(options)
        {
        }

        public DbSet<Empleado> Empleados { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
                       
        }
    }
}

CoreFirebase/Models/Empleado.cs
namespace CoreFirebase.Models
{
    public class Empleado
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public string? Telefono { get; set; }
        public string? URLImagen { get; set; }
    }
}

CoreFirebase/Models/ErrorViewModel.cs
namespace CoreFirebase.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreFirebase/Controllers/EmpleadosController.cs
using CoreFirebase.Helpers;
using CoreFirebase.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CoreFirebase.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly DataContext _context;
        private readonly IUploadStorage _uploadStorage;

        public EmpleadosController(DataContext context,IUploadStorage uploadStorage )
        {
            _context = context;
            _uploadStorage = uploadStorage;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Empleados                
                .ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Empleado empleado, IFormFile Imagen)
        {
            if (ModelState.IsValid)
            {

                //RECIBIR LOS DATOS DEL FORMULARIO
                Stream image = Imagen.OpenReadStream();
                string urlimagen = await _uploadStorage.SubirStorage(image, Imagen.FileName);

                try
                {
                    empleado.URLImagen = urlimagen;
                    _context.Add(empleado);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception exception)
                {
                    ViewBag.Error(exception.Message);
                }
            }
            return View(empleado);
        }
    }
}

CoreFirebase/Controllers/HomeController.cs
using CoreFirebase.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CoreFirebase.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CoreFirebase/Views/Empleados/Create.cshtml
@model Empleado
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="card">
    <div class="card-header bg-dark text-white">
        Crear Empleado
    </div>
    <div class="card-body">
        <form asp-action="Create" asp-controller="Empleados" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label class="form-label">Nombre</label>
                <input type="text" class="form-control" asp-for="Nombre" autocomplete="off">
            </div>
            <div class="mb-3">
                <label class="form-label">Telefono</label>
                <input type="text" class="form-control" asp-for="Telefono" autocomplete="off">
            </div>
            <div class="mb-3">
                <input type="file" class="form-control" name="Imagen">
            </div>
            <button type="submit" class="btn btn-primary">Guardar</button>
            <a asp-action="Index" asp-controller="Empleado" class="btn btn-warning">Volver a lista</a>
        </form>
    </div>
</div>

CoreFirebase/Views/Empleados/Index.cshtml
@model List<Empleado>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="card">
    <div class="card-header bg-dark text-white">
        Lista de empleados
    </div>
    <div class="card-body">
        <a asp-action="Create" asp-controller="Empleados" class="btn btn-success">Crear Nuevo</a>
        <hr />
        <table class="table table-bordered">
            <thead class="table-dark text-white">
                <tr>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Foto</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Nombre</td>
                        <td>@item.Telefono</td>
                        <td>
                            <img src="@item.URLImagen" width="100" height="100">
                        </td>

                    </tr>


                }
            </tbody>
        </table>
    </div>
</div>

CoreFirebase/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreFirebase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreFirebase</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoreFirebase.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreFirebase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CoreFirebase - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>